Vagrant.configure("2") do |config|
	config.vm.box = "generic/rhel9"
	config.vm.box_check_update = true
	config.vm.hostname = "testrhel9"
	config.vm.network "private_network", ip: "192.168.56.90"
	config.vm.synced_folder "." "/vagrant", disabled: true
# attach iso
	config.vm.provision 'file', source: '/usr/share/virtualbox/VBoxGuestAdditions.iso', destination: '/tmp/VBoxGuestAdditions.iso'
# shell configuration
	config.vm.provision "shell" do |s|
		s.env = {
			"SUB_USERNAME_VAR":ENV['SUB_USERNAME'],
			"SUB_PASSWORD_VAR":ENV['SUB_PASSWORD']
		}
		s.path = 'scripts/postinstall.sh'

	end
end

